const withPWA = require('next-pwa')({
  dest: 'public',
  register: true,
  skipWaiting: true,
  disable: process.env.NODE_ENV !== 'production',
});

module.exports = withPWA({
  images: {
    domains: [
      'cdn.cnn.com',
      'ichef.bbci.co.uk',
      'static01.nyt.com',
      'media.guim.co.uk',
      'assets.bwbx.io',
      'images.wsj.net',
      's.yimg.com',
      'img.youtube.com',
      'www.aljazeera.com',
      'www.reuters.com',
      'pagesix.com',
      'cdn.mos.cms.futurecdn.net',
      'media.eventhubs.com',
      'images.nintendolife.com',
      'media.cnn.com',
      'static.standard.co.uk',
      'media.gq.com',
      'images.axios.com',
      'media.vanityfair.com',
      'img.etimg.com',
      'images.indianexpress.com',
      'img.huffingtonpost.com',
      'media.standard.co.uk',
      'ichef-1.bbci.co.uk',
      'ichef-2.bbci.co.uk',
      'ichef-3.bbci.co.uk',
      'ichef-4.bbci.co.uk',
      'ichef-5.bbci.co.uk',
      'ichef-6.bbci.co.uk',
      'ichef-7.bbci.co.uk',
      'ichef-8.bbci.co.uk',
      'ichef-9.bbci.co.uk',
      'ichef-10.bbci.co.uk',
      'ichef-11.bbci.co.uk',
      'ichef-12.bbci.co.uk',
      'ichef-13.bbci.co.uk',
      'ichef-14.bbci.co.uk',
      'ichef-15.bbci.co.uk',
      'ichef-16.bbci.co.uk',
      'ichef-17.bbci.co.uk',
      'ichef-18.bbci.co.uk',
      'ichef-19.bbci.co.uk',
      'image.cnbcfm.com',
      'assetsio.gnwcdn.com',
      'www.hollywoodreporter.com',
    ],
    formats: ['image/webp', 'image/avif'],
    deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840],
    imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
    minimumCacheTTL: 60,
  },
  experimental: {
    optimizeCss: true,
    optimizePackageImports: ['react-icons'],
  },
  // يمكنك إضافة إعدادات Next.js هنا
}); 